const boardGames =
[
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    },
    {
    GameNr:1,
    Genre:"Genre",
    Designer:"designer",
    Title:"Title",
    Description:"description",
    Picture:"apple.jpeg",
    Score: "4",
    }
];