const boardGames =
[
    {
    GameNr:1,
    PlayerNr:"1-4",
    Designer:"I. Childres",
    Title:"Gloomhaven",
    Description:"Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy!",
    Picture:"./imagesCollection/gloomhaven.jpg",
    Score: "8.7",    
    Link: "https://boardgamegeek.com/boardgame/174430/gloomhaven",
    },
    {
    GameNr:1,
    PlayerNr:"2-4",
    Designer:"M. Leacock",
    Title:"Pandemic Legacy",
    Description:"Mutating diseases are spreading around the world - can your team save humanity?",
    Picture:"./imagesCollection/pandemic.png",
    Score: "8.6",
    Link: "https://boardgamegeek.com/boardgame/161936/pandemic-legacy-season-1",
    },
    {
    GameNr:1,
    PlayerNr:"2-4",
    Designer:"M. Wallace",
    Title:"Brass Birmingham",
    Description:"Build networks, grow industries, and navigate the world of the Industrial Revolution.",
    Picture:"./imagesCollection/birmingham.jpg",
    Score: "8.7",
    Link: "https://boardgamegeek.com/boardgame/224517/brass-birmingham",
    },
    {
    GameNr:1,
    PlayerNr:"1-5",
    Designer:"J. Fryxelius",
    Title:"Terraforming Mars",
    Description:"Compete with rival CEOs to make Mars habitable and build your corporate empire.",
    Picture:"./imagesCollection/mars.jpg",
    Score: "8.3",
    Link: "https://boardgamegeek.com/boardgame/167791/terraforming-mars",
    },
    {
    GameNr:1,
    PlayerNr:"3-8",
    Designer:"C. Peterson",
    Title:"Twilight Imperium 4",
    Description:"Build an intergalactic empire through trade, research, conquest and grand politics.",
    Picture:"./imagesCollection/twilight.jpg",
    Score: "8.3",
    Link: "https://boardgamegeek.com/boardgame/233078/twilight-imperium-fourth-edition",
    },
    {
    GameNr:1,
    PlayerNr:"2-4",
    Designer:"J. Drogemuller",
    Title:"Gaia Project",
    Description:"Expand, research, upgrade, and settle the galaxy with one of 14 alien species.",
    Picture:"./imagesCollection/gaia.png",
    Score: "8.2",
    Link: "https://boardgamegeek.com/boardgame/220308/gaia-project",
    },
    {
    GameNr:1,
    PlayerNr:"2-4",
    Designer:"C. Konieczka",
    Title:"Starwars Rebellion",
    Description:"Strike from your hidden base as the Rebels—or find and destroy it as the Empire.",
    Picture:"./imagesCollection/star.jpg",
    Score: "8.4",
    Link: "https://boardgamegeek.com/boardgame/187645/star-wars-rebellion",
    },
    {
    GameNr:1,
    PlayerNr:"2-4",
    Designer:"E. Reus",
    Title:"Spirit Island",
    Description:"Island Spirits join forces using elemental powers to defend their home from invaders.",
    Picture:"./imagesCollection/spirit.png",
    Score: "8.4",
    Link: "https://boardgamegeek.com/boardgame/162886/spirit-island",
    },
    {
    GameNr:1,
    PlayerNr:"2-4",
    Designer:"A. Pfister",
    Title:"Great Western Trail",
    Description:"Use strategic outposts and navigate danger as you herd your cattle to Kansas City.",
    Picture:"./imagesCollection/Great.jpg",
    Score: "8.3",
    Link: "https://boardgamegeek.com/boardgame/193738/great-western-trail",
    },
    {
    GameNr:1,
    PlayerNr:"2-6",
    Designer:"M. Gerdts",
    Title:"Imperial 2030",
    Description:"Use money to manipulate countries into warring with each other for your own profit.",
    Picture:"./imagesCollection/2030.jpg",
    Score: "10",
    Link: "https://boardgamegeek.com/boardgame/54138/imperial-2030",
    }
];